### ISSUE TITLE
Main `index.ts` not being created using `barrelType: 'all'`

### ISSUE THREAD

**Issue by burt202** [kubb-labs/kubb#1398]
### What version of `kubb` is running?

3.0.5

### What platform is your computer?

Linux

### What version of external packages are you using(`@tanstack-query`, `MSW`, `React`, `Vue`, ...)

See linked repo below

### What steps can reproduce the bug?

Im trying to upgrade our setup to v3, which takes a yml openapi docs link and spits out generated TS for it. In v2, an `index.ts` file gets created alongside the `types.ts` but i cant seem to get this working in v3. Im aware of the new `barrelType` option and think im using it correctly to the [docs](https://kubb.dev/getting-started/configure#output-barreltype)

For repro, clone repo linked below and npm ci and npm run generate

https://github.com/burt202/kubb-test/tree/master

Any help would be appreciated as to what im doing wrong. Cheers!

### How often does this bug happen?

Every time

### What is the expected behavior?

Index file should be created with the contents `export * from "./types"`

**Comment by stijnvanhulle** [comment]
`v3.0.6` will resolve your issue.

**Comment by burt202** [comment]
Thanks for the quick reply. This is still not working for me using `v3.0.6`  using the following config:

```
import {defineConfig}  from '@kubb/core'
import {pluginOas}  from '@kubb/plugin-oas'
import {pluginTs}  from '@kubb/plugin-ts'

export default defineConfig({
  root: '.',
  input: {
    path: 'docs/main.yml'
  },
  output: {
    path: 'generated/',
    barrelType: 'all',
    clean: true
  },
  plugins: [
    pluginOas({
      generators: [],
    }),
    pluginTs({
      output: {
        path: "./types.ts",
        barrelType: 'propagate'
      }
    })
  ]
})
```

Repro code: https://github.com/burt202/kubb-test

The generation runs without error but no `index.ts` file is created.
Where am I going wrong?

Cheers!

**Comment by stijnvanhulle** [comment]
@burt202 If a generated plugin was a single file(.ts) then it was not being exported. This has been resolved with 3.0.7

**Comment by burt202** [comment]
Thanks for the new version. With `3.0.7` the `index.ts` file is being created! The contents though are:

```
export type { LoginRequest, AuthTokenResponse, PostLogin200, PostLoginMutationRequest, PostLoginMutationResponse, PostLoginMutation } from "./types.ts";
```

Would you expect the contents to be...

```
export * from "types.ts";
```

...when using `barrelType: "all` on the top level?

Cheers

**Comment by stijnvanhulle** [comment]
@burt202 I missed that one but fixed in 3.0.9. That should normally be the final fix to make it work for you :)

**Comment by burt202** [comment]
Thanks `3.0.9` fixes the `index.ts` content to `export type * from "./types.ts";` Thanks!

This still isnt quite parity with v2 though as this export only targets types and doesnt export enums that are `consts`. 
v2 was `export * from "./types.ts";`

Ive updated my test repo with an enum so you can reproduce: https://github.com/burt202/kubb-test

I think this also highlights that the `enumSuffix` default `''` doesnt apply to the const enums because i get the following in the generated output:

```
export const loginTypeEnumEnum = {
    "user": "user",
    "admin": "admin"
} as const;
```

Sorry to be a pain. Your help and speed in fixing these issues is massively appreciated. Cheers!

**Comment by stijnvanhulle** [comment]
`enumSuffix` was in v2 by default '' but in v3 it has a default of `enum`. This was changed to make sure that named imports could work, even if some enums are named the same in your Swagger/OpenAPI.

**Comment by burt202** [comment]
Yep, all good. Many thanks!
